.devcontainer/docker-compose.yml
Some images in use define volumes in their docker file. Without a named volume, unnamed volumes are created on container start and build up over time. By defining these volumes int he docker-compose, we can prevent the build up of unnamed volumes.
=> docker-compose: prevent unnamed volumes

.devcontainer/README.md, .devcontainer/devserver_config/oidc/conf.json, .devcontainer/docker-compose.yml, .devcontainer/entrypoint.d/270_adjust_oidc_conf.sh, README.md
It was found that when using anywhere, a redirect in a webview to domain 'keycloak' was causing an error to be thrown. Changing the domain to 'keycloak.local' fixes the issue.
=> keycloak: updated template to use service name keycloak.local

.devcontainer/README.md, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .devcontainer/dockerfile, .devcontainer/remote_host/README.md, .devcontainer/remote_host/devcontainer.json, .devcontainer/remote_host/docker-compose-shared.yml, .devcontainer/remote_host/docker-compose.yml, .gitignore, deployment/README.md
Changes to template to better support remote dev containers (hosted on development servers)
- added new folder `remote_host` to hold these new configurations 
-compose: split iqgeo service to allow inheritance
-adjust for apache port now being 8080 (this is to match the new platform-devenv image, which was changed for consistency and better support for port forwarding to local machines)
-adjust file permissions and UID mapping
corresponding PR in utils-docker-platform: https://github.com/IQGeo/utils-docker-platform/pull/272
=> devcontainer: added remote host configurations

.devcontainer/remote_host/docker-compose.yml
When connecting to a remote host through SSH, the Keycloak default port was set to 8081. To ensure this works without updating the .env file, the default port had to be updated for the iqgeo service too.
=> devcontainer: Updated Keycloak default port definitions to 8081

.devcontainer/remote_host/README.md, .devcontainer/remote_host/docker-compose.yml
Changes made
- Updated `remote_host/README.md` to give instruction to update the devcontainer.json if the keycloak port changes.
- Added default IQGEO_HOST to `remote_host/docker-compose.hml`. Without this setting, port forwarding does not work as the redirect sent to Keycloak uses port 80
=> remote_host: set default IQGEO_HOST and updated README.md

.devcontainer/remote_host/devcontainer.json, .devcontainer/remote_host/docker-compose.yml
A recommendation from Daniel Indigo.
Since we need IQGEO_HOST and MYW_EXT_BASE_URL to be set to `localhost:8080` when running using the dev container extension, we can add the values to the `devcontainer.json` to ensure they are not overwritten by the user of a .env when running from dev container extension.
=> remote-host: moved env values for dev container to devcontainer.json

deployment/dockerfile.appserver, deployment/dockerfile.tools
There are some complaints about syntax in some linting that is running. These changes address those warnings.
=> use `AS` keyword all-caps, not `as`

.iqgeorc.jsonc, README.md
We could add additional notes for `cosmof_dev_db` and `electric_dev_db`. Just focused on product modules in this PR.
Relates to https://iqgeo.atlassian.net/browse/PLAT-10616
=> PLAT-10616: added project module dependencies to readme.

.devcontainer/docker-compose.yml, deployment/docker-compose.yml
The location of the PostGIS image provided by IQGeo has changed. This PR updates the image location and bumps it to use the latest PostGIS 3.5 version for PostgreSQL 12.
Note: The previous image is still available and will work without issue.
=> docker-compose: docker-compose: updated postgis image used to 12-3.5.

.devcontainer/remote_host/devcontainer.json
Updated the `devcontainer.json` in remote_host to allow developers to connect to `pgadmin` from their host machine. I think this makes since `pgadmin` is included in the shared services.
TODO:
Going to update the README.md found in the remote_host directory with instructions on accessing pgadmin.
=> remote_host: added forwardPort value for pgadmin in devcontainer.json

.devcontainer/remote_host/docker-compose-shared.yml
Missed removing memached from remote_hosts shared services.  
Should get this merged ASAP as it will cause issues trying to started the shared services from the remote host directory.
=> bug/remove memcached from remote_host shared services

.devcontainer/docker-compose.yml
Updated rq-dashboard name defined in the devcontainer docker-compose to use _${PROJ_PREFIX:-myproj} to prevent name conflicts.
=> docker-compose: updated rq-dashboard with paramaterized name

.devcontainer/remote_host/docker-compose.yml
Missed in a recent refactor to  ${KEYCLOAK_HOST}. Seemed to overlook the remote_hosts directory.
=> docker-compose: fixed KEYCLOAK_HOST url in remote_hosts/docker-compose

.devcontainer/dockerfile, deployment/dockerfile.build
would cause problems when using containerd image store.
To match change in https://github.com/IQGeo/utils-project-update/pull/15
=> dockerfile: remove use of COPY --link when using --from

.devcontainer/remote_host/devcontainer.json
Added port forwarding of the rq-dashboard container for remote host devcontainer.json. Without this the rq-dashboard is not reachable when using a remote host.
=> Added port forwarding of the rq-dashboard container for remote host devcontainer.json

.devcontainer/docker-compose.yml
The defined Redis environment variable for rq-dashboard was incorrect not consistent with other location in the docker-compose
=> docker-compose: added rq-dashboard do depends_on so it starts when using dev container extension

.devcontainer/docker-compose.yml, .iqgeorc.jsonc, deployment/docker-compose.yml
Updates the postgis version to 15. 
The timing of this merge should coincide with an announcement. Should a team or developer choose to update their project to the latest version of the template, the version change will impact their development environments as their existing database was built and ran under v12.
The service will fail to start with the following error:
```
2024-11-27 16:31:18.726 UTC [1] FATAL:  database files are incompatible with server
2024-11-27 16:31:18.726 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 15.8 (Debian 15.8-1.pgdg110+1).
```
=> docker-compose: updated PostGIS to 15-3.5

.devcontainer/docker-compose.yml, .devcontainer/dockerfile, .iqgeorc.jsonc, deployment/docker-compose.yml, deployment/dockerfile.appserver, deployment/dockerfile.build, deployment/dockerfile.tools
Updates container registry paths for new registry organisation.
introduces PRODUCT_REGISTRY env variable, replacing CONTAINER_REGISTRY, so paths don't become incorrect if that variable is being set to point to a customer specific folder in the registry.
Note: I believe this is complete but it is still in draft because it requires the images to be in the new locations so it can be tested appropriately - which needs to be done before merging
=> ET-274: update container registry paths for new registry organisation

.devcontainer/docker-compose.yml, .gitignore, .iqgeorc.jsonc, tsconfig.json
There's a mismatch between how Webpack and TypeScript resolve module paths. Namely, `modules/<module>/*` is mapped to `./<module>/public/*`. This can't be fixed by defining static paths in [core](https://github.com/IQGeo/myworld-product-core/blob/master/WebApps/myworldapp/modules/tsconfig.core.json), because TypeScript only allows one wildcard in a path, so we can't do `./*/public/*`.
This PR adds a tsconfig.json file that the project-update tool can dynamically populate with path mappings for each module defined in .iqgeorc.jsonc.
https://github.com/IQGeo/utils-project-update/pull/18
I went through each path defined in tsconfig.core.json and tried them in the comms repo, removing any that didn't work. Some only worked in certain directories, so there's a chance I've removed some that …
=> PLAT-11234: add tsconfig

.devcontainer/dockerfile, .iqgeorc.jsonc, deployment/dockerfile.appserver, deployment/dockerfile.build, tsconfig.json
Someone that creates a new project/repo from the template, and just runs the update will get some file changes that wouldn't be expected, as they're not from any changes to the .iqgeorc.jsonc. They're just files that were left out of sync.
This aligns those files
=> Align files with initial state of .iqgeorc.jsonc

.devcontainer/docker-compose.yml
Seems to cause issues to some teams when things are touched by a different user (build triggered by task) and are then hard to fix because the volume keeps the permissions on those files
I don't think this is  needed anymore since we always start a build on startup.
=> devcontainer: remove volume to keep js bundles

.devcontainer/docker-compose.yml
Add environment variable ROPC_ENABLE to allow for api authentication.
=> PLAT-10007: docker: Add ROPC_ENABLE as environment variable to iqgeo-common

.devcontainer/docker-compose.yml
A bit higher, LRT is configured to use db 1 by default: https://github.com/IQGeo/utils-project-template/blob/d7daabc503ea9ee622aaa4ae96874a73f31d3d37/.devcontainer/docker-compose.yml#L50
If RQ dashboard is not configured to look at the same redis db, you cannot see your tasks and workers.
=> .devcontainer: RQ dashboard URL consistent with LRT URL

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml
The dev container, when run through the extension, will only start containers defined in the depends_on section or specified via runServices in devcontainer.json. The pattern we've selected is to define these services in depends_on.
Changes:
- Added rq-dashboard to the depends_on section of the Compose YAML.
- Fixed the default Redis connection string set for the rq-dashboard service.
=> .devcontainer: rq-dashboard changed to trigger on container start

.devcontainer/docker-compose.yml
With a recent docker update, docker interprets some default values differently. This PR allows the user to manually override the SSL_REQUIRED variable for local development.
=> Add SSL_REQUIRED

.devcontainer/devcontainer.json, .devcontainer/dockerfile, .iqgeorc.jsonc, deployment/dockerfile.appserver, deployment/dockerfile.build, deployment/dockerfile.tools
This PR updates the default platform version from 7.3 to 7.4. This branch was tested by changing the platform version to 7.4 running the IQGeo updated vscode feature to update relevant files. Then the running app was inspected to check the app behaved as expected.
=> Upgrade the default platform version to 7.4
